name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Vsce Package
        run: npx vsce package

      - name: Vsce Publish
        run: npx vsce publish -p ${{ secrets.GH_TOKEN }}
